import os
import re
from datetime import datetime
import logging

# Configure logger
logger = logging.getLogger(__name__)

class MarkdownGenerator:
    def __init__(self, output_dir: str = "drafts", json_file: str = "bills.json"):
        """Initialize the generator with an output directory and json file."""
        self.output_dir = output_dir
        self.json_file = json_file
        
        # Ensure the directory exists
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def sanitize_filename(self, text: str) -> str:
        """Sanitize a string to be used as a valid filename."""
        text = text.lower()
        # Remove anything that isn't alphanumeric, space, or hyphen
        text = re.sub(r'[^a-z0-9\s\-]', '', text)
        # Replace spaces with hyphens
        text = re.sub(r'\s+', '-', text)
        return text

    def generate_draft(self, bill_info: dict, analysis: dict):
        """
        Generate a Markdown file for the bill with YAML frontmatter.
        """
        date_str = datetime.now().strftime("%Y-%m-%d")
        
        bill_number = bill_info.get("bill_number", "Unknown")
        state = bill_info.get("state", "Unknown")
        status = bill_info.get("last_action", "Unknown")
        title = bill_info.get("title", "No Title")
        bill_id = bill_info.get("bill_id", "No-ID")
        
        impact_score = analysis.get("impact_score", "N/A")
        
        # Format the frontmatter
        frontmatter = f"""---
date: {date_str}
state: {state}
bill_number: "{bill_number}"
bill_id: {bill_id}
status: "{status}"
impact_score: "{impact_score}"
---
"""
        
        # Format the body
        exec_summary = analysis.get("executive_summary", "")
        impact_expl = analysis.get("impact_explanation", "")

        body = f"# {title}\n\n"
        
        body += "## Executive Summary\n\n"
        if exec_summary:
            body += f"{exec_summary}\n\n"
        else:
            body += "No summary available.\n\n"
            
        body += "## Output Analysis & Business Impact\n\n"
        
        body += f"**South Carolina Business Impact Score:** {impact_score}/10\n\n"
        
        if impact_expl:
            body += f"{impact_expl}\n\n"
        else:
            body += "No impact explanation available.\n\n"
            
        body += "---\n\n"
        body += f"*Generated by the Legislative Watchdog Engine for SCAIO on {date_str}*\n"
        body += f"*Last Action: {status} on {bill_info.get('last_action_date', 'Unknown')}*\n"
        if bill_info.get('text_url'):
            body += f"*[View Full Bill Text on LegiScan]({bill_info.get('text_url')})*\n"

        # Construct the file name
        safe_title = self.sanitize_filename(title)[:50] # Limit length
        filename = f"{date_str}-{state}-{bill_number}-{safe_title}.md"
        filepath = os.path.join(self.output_dir, filename)
        
        try:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(frontmatter + "\n" + body)
            logger.info(f"Successfully drafted: {filepath}")
            
            # Update the JSON database
            self.update_json_database(bill_info, analysis, date_str)
            
            return filepath
        except IOError as e:
            logger.error(f"Failed to write markdown file {filepath}: {e}")
            return None

    def update_json_database(self, bill_info: dict, analysis: dict, current_date: str):
        """
        Appends or updates the bill in the centralized JSON database.
        """
        import json
        
        bill_id = str(bill_info.get("bill_id"))
        
        # Load existing data
        data = []
        if os.path.exists(self.json_file):
            try:
                with open(self.json_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
            except Exception as e:
                logger.warning(f"Failed to load existing json database: {e}")
                
        # Create new record
        record = {
            "id": bill_id,
            "bill_number": bill_info.get("bill_number", "unknown"),
            "state": bill_info.get("state", "unknown"),
            "date_processed": current_date,
            "status": bill_info.get("last_action", "unknown"),
            "impact_score": analysis.get("impact_score", "N/A"),
            "title": bill_info.get("title", "No Title"),
            "summary": analysis.get("executive_summary", ""),
            "explanation": analysis.get("impact_explanation", ""),
            "url": bill_info.get("text_url", "")
        }
        
        # Check if record already exists, if so update it, otherwise append
        existing_idx = next((i for i, item in enumerate(data) if item["id"] == bill_id), -1)
        if existing_idx >= 0:
            data[existing_idx] = record
        else:
            data.append(record)
            
        # Write back to file
        try:
            with open(self.json_file, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2)
            logger.info(f"Successfully updated json database: {self.json_file}")
        except IOError as e:
            logger.error(f"Failed to write json database: {e}")
